package seeder

import (
	"errors"

	"github.com/zetsux/gin-gorm-clean-starter/core/entity"
	"gorm.io/gorm"
)

func AnimalSeeder(db *gorm.DB, animalTypeMap map[string]string) (map[string]string, error) {
	var dummyAnimals = []entity.Animal{
		{
			Name:               "Buaya",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               1,
			Hint:               "Hewan reptil air yang memiliki rahang sangat kuat",
			Description:        "Buaya adalah predator air tawar dan asin yang sangat kuat, dengan rahang yang dapat menghancurkan tulang.",
			Habitat:            "Sungai, danau, rawa, dan beberapa wilayah pantai",
			Food:               "Ikan, mamalia, dan burung",
			Reproduction:       "Bertelur",
			FunFact:            "Buaya dapat hidup hingga lebih dari 70 tahun di alam liar.",
			ConservationStatus: "Bergantung pada spesies; beberapa genting",
			BadgeImage:         "badge_picture/85f4b75d-a723-4c13-b19e-f7aa4dd15bc1.png",
			RealImage:          "animal_picture/5aa41bb3-a753-4786-a03e-72dfe54b6e5c.png",
			SilhouetteImage:    "silhouette_picture/d27257b7-3511-4dfa-b938-b589f87bc384.png",
		},
		{
			Name:               "Ular Kobra",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               2,
			Hint:               "Dikenal dengan leher yang dapat mengembang",
			Description:        "Ular Kobra adalah jenis ular berbisa yang terkenal karena bisa mengembangkan lehernya yang lebar saat merasa terancam.",
			Habitat:            "Padang rumput, hutan, dan daerah pertanian",
			Food:               "Amfibi, ikan kecil, dan reptil lain",
			Reproduction:       "Bertelur",
			FunFact:            "Kobra dapat 'berjalan' dengan mengangkat sepertiga tubuhnya saat merasa terancam.",
			ConservationStatus: "Bergantung pada spesies; beberapa genting",
			BadgeImage:         "badge_picture/b628e3f3-953d-46a1-93d8-218acc779335.png",
			RealImage:          "animal_picture/063f942d-bca0-4a5f-b34c-b8326f4cb1a9.png",
			SilhouetteImage:    "silhouette_picture/12c7f591-3978-4c79-89d1-df510c8a39f6.png",
		},
		{
			Name:               "Komodo",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               3,
			Hint:               "Reptil besar dari Indonesia yang dapat berlari cepat",
			Description:        "Komodo adalah spesies kadal terbesar di dunia yang dikenal karena ukuran dan keganasannya.",
			Habitat:            "Pulau-pulau kering dan berbatu",
			Food:               "Rusa, babi, dan bangkai",
			Reproduction:       "Bertelur",
			FunFact:            "Komodo memiliki racun dalam gigitannya yang membantu melumpuhkan mangsanya.",
			ConservationStatus: "Terancam Punah (Endangered)",
		},
		{
			Name:               "Bunglon",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               4,
			Hint:               "Dapat mengubah warna kulitnya",
			Description:        "Bunglon adalah reptil yang memiliki kemampuan unik untuk mengubah warna kulitnya, membantu kamuflase atau mengatur suhu tubuhnya.",
			Habitat:            "Hutan dan area semak",
			Food:               "Serangga dan invertebrata kecil lainnya",
			Reproduction:       "Bertelur",
			FunFact:            "Warna kulit bunglon tidak hanya berubah untuk kamuflase tetapi juga sebagai komunikasi selama periode kawin atau ketika terancam.",
			ConservationStatus: "Bergantung pada spesies",
		},
		{
			Name:               "Biawak",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               5,
			Hint:               "Reptil yang mirip komodo tetapi lebih kecil",
			Description:        "Biawak adalah anggota dari keluarga kadal besar yang dapat ditemukan di berbagai habitat, termasuk di perairan tawar dan hutan.",
			Habitat:            "Hutan, rawa, dan sungai",
			Food:               "Ikan, burung, dan telur",
			Reproduction:       "Bertelur",
			FunFact:            "Biawak memiliki kemampuan berenang yang sangat baik dan sering memanjat pohon untuk mencari telur burung.",
			ConservationStatus: "Bergantung pada spesies",
		},
		{
			Name:               "Ular Sanca Kembang",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               6,
			Hint:               "Ular besar yang melilit mangsanya",
			Description:        "Ular Sanca Kembang adalah jenis ular piton yang dikenal karena kekuatan melilitnya, yang digunakan untuk membatasi pernapasan mangsanya hingga mati.",
			Habitat:            "Hutan hujan tropis dan area yang berdekatan dengan sumber air",
			Food:               "Mamalia kecil dan burung",
			Reproduction:       "Melahirkan",
			FunFact:            "Meskipun besar dan menakutkan, ular ini jarang menyerang manusia kecuali terprovokasi atau dalam kondisi terancam.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Penyu Hijau",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               7,
			Hint:               "Hewan laut yang kembali ke pantai kelahirannya untuk bertelur",
			Description:        "Penyu Hijau adalah salah satu spesies penyu yang sering ditemukan di perairan tropis dan subtropis di seluruh dunia.",
			Habitat:            "Laut terbuka dan pantai berpasir untuk bertelur",
			Food:               "Rumput laut dan invertebrata laut",
			Reproduction:       "Bertelur di pantai",
			FunFact:            "Penyu Hijau dapat melakukan migrasi jarak jauh antara area makan mereka di laut dan pantai tempat mereka bertelur.",
			ConservationStatus: "Terancam Punah",
		},
		{
			Name:               "Penyu Belimbing",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               9,
			Hint:               "Memiliki cangkang berbentuk bintang",
			Description:        "Penyu Belimbing adalah salah satu dari spesies penyu terbesar, dikenal dengan cangkangnya yang memiliki pola seperti bintang.",
			Habitat:            "Laut terbuka dan pantai berpasir",
			Food:               "Ubur-ubur dan invertebrata lainnya",
			Reproduction:       "Bertelur di pantai",
			FunFact:            "Penyu Belimbing memiliki kemampuan untuk menyelam hingga kedalaman lebih dari 1200 meter, membuatnya menjadi salah satu penyelam terdalam di antara reptil.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Cicak Tokek",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               10,
			Hint:               "Dikenal karena suaranya yang khas",
			Description:        "Cicak Tokek adalah jenis cicak yang dikenal karena kemampuannya memanjat dinding dan suara uniknya yang keras, sering terdengar di malam hari.",
			Habitat:            "Rumah-rumah dan hutan",
			Food:               "Serangga dan invertebrata kecil lainnya",
			Reproduction:       "Bertelur",
			FunFact:            "Tokek dikenal karena kemampuan mereka untuk 'menempel' di permukaan yang sangat halus, berkat struktur mikroskopis pada kakinya.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Ular Weling",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               11,
			Hint:               "Ular berbisa dengan pola warna yang mencolok",
			Description:        "Ular Weling adalah ular berbisa yang ditemukan di Asia Tenggara, terkenal dengan pola belang hitam dan putih pada tubuhnya.",
			Habitat:            "Hutan, lahan pertanian, dan daerah berbatu",
			Food:               "Amfibi, reptil kecil, dan kadang-kadang mamalia kecil",
			Reproduction:       "Melahirkan",
			FunFact:            "Ular ini kadang-kadang 'berpura-pura' mati untuk menghindari pemangsa.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Ular Kapak Hijau",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               12,
			Hint:               "Memiliki keunikan pada bentuk kepala yang pipih dan lebar",
			Description:        "Ular Kapak Hijau adalah spesies ular yang tidak berbisa, dikenal karena kepala pipih dan lebarnya yang membantu dalam kamuflase di antara dedaunan.",
			Habitat:            "Hutan hujan",
			Food:               "Serangga, terutama belalang dan kumbang",
			Reproduction:       "Bertelur",
			FunFact:            "Ular ini sering ditemukan tergantung diam di cabang pohon, hampir tidak terdeteksi karena mimikri dengan lingkungannya.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Kadal",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               13,
			Hint:               "Reptil kecil yang sering ditemukan di dinding atau pohon",
			Description:        "Kadal adalah reptil kecil yang umum dan beragam, dengan kemampuan adaptasi yang tinggi di berbagai habitat.",
			Habitat:            "Dari padang pasir hingga hutan tropis",
			Food:               "Serangga, arakhnida, dan invertebrata kecil lainnya",
			Reproduction:       "Bertelur dan beberapa spesies melahirkan",
			FunFact:            "Beberapa spesies kadal dapat memutuskan ekornya untuk melarikan diri dari pemangsa dan kemudian meregenerasi bagian tersebut.",
			ConservationStatus: "Bergantung pada spesies; banyak yang kurang prihatin",
		},
		{
			Name:               "Penyu Lekang",
			AnimalTypeID:       animalTypeMap["Reptil"],
			Step:               14,
			Hint:               "Penyu yang lebih sering ditemukan di perairan Asia Tenggara",
			Description:        "Penyu Lekang adalah penyu yang lebih kecil dibandingkan dengan kerabatnya, sering ditemukan di perairan dangkal di Asia Tenggara.",
			Habitat:            "Perairan dangkal, terumbu karang, dan muara",
			Food:               "Alga, rumput laut, dan invertebrata kecil",
			Reproduction:       "Bertelur di pantai",
			FunFact:            "Penyu Lekang adalah salah satu dari sedikit spesies penyu yang dapat bertahan hidup di air payau.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Elang Jawa",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               1,
			Hint:               "Burung pemangsa ini adalah lambang nasional Indonesia",
			Description:        "Elang Jawa adalah burung pemangsa yang endemik di pulau Jawa dan merupakan simbol nasional Indonesia, dikenal dengan kemampuannya yang luar biasa dalam berburu.",
			Habitat:            "Hutan pegunungan dan hutan hujan",
			Food:               "Mamalia kecil, burung lain, dan reptil",
			Reproduction:       "Bertelur",
			FunFact:            "Elang Jawa memiliki rentang sayap yang bisa mencapai hampir 2 meter.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Cenderawasih",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               2,
			Hint:               "Burung dengan bulu yang sangat indah dan berwarna-warni",
			Description:        "Cenderawasih adalah kelompok burung yang dikenal karena bulu yang sangat indah dan warna yang mencolok, menjadi simbol dari Papua.",
			Habitat:            "Hutan tropis di Papua dan pulau-pulau sekitarnya",
			Food:               "Buah-buahan, serangga, dan nektar",
			Reproduction:       "Bertelur",
			FunFact:            "Parade kawin cenderawasih yang rumit dan berwarna-warni adalah salah satu tontonan paling menarik di dunia alam.",
			ConservationStatus: "Bergantung pada spesies; beberapa genting",
		},
		{
			Name:               "Jalak Bali",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               3,
			Hint:               "Burung kecil yang hampir punah dari Bali",
			Description:        "Jalak Bali adalah spesies burung yang sangat terancam punah, endemik di pulau Bali, dikenal karena bulunya yang terang dan perilaku sosialnya.",
			Habitat:            "Hutan kering dan area pertanian di sekitar Bali",
			Food:               "Buah, biji-bijian, dan serangga",
			Reproduction:       "Bertelur",
			FunFact:            "Populasi Jalak Bali di alam liar sangat sedikit, membuatnya menjadi salah satu burung paling langka di dunia.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Beo Nias",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               4,
			Hint:               "Burung yang dapat menirukan suara manusia",
			Description:        "Beo Nias adalah burung pintar yang bisa menirukan berbagai suara, termasuk suara manusia, membuatnya populer di kalangan pecinta burung.",
			Habitat:            "Hutan subtropis dan tropis, serta area pedesaan dan taman",
			Food:               "Buah-buahan, biji-bijian, dan serangga",
			Reproduction:       "Bertelur",
			FunFact:            "Beo Nias memiliki kemampuan untuk menirukan suara yang sangat kompleks dan dapat mempelajari kata-kata atau frasa.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Kakatua Raja",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               5,
			Hint:               "Memiliki jambul kuning mencolok",
			Description:        "Kakatua Raja adalah burung yang besar dengan jambul kuning cerah, sangat terkenal karena penampilannya yang mencolok dan sifatnya yang ramah.",
			Habitat:            "Hutan tropis dan area dengan pohon besar",
			Food:               "Buah-buahan, kacang-kacangan, dan biji-bijian",
			Reproduction:       "Bertelur",
			FunFact:            "Kakatua Raja dapat hidup sangat lama, dengan umur di penangkaran bisa mencapai lebih dari 50 tahun.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Enggang Gading",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               6,
			Hint:               "Burung dengan paruh besar dan melengkung",
			Description:        "Enggang Gading, juga dikenal sebagai Burung Rangkong, adalah spesies burung berparuh besar yang dikenal karena perannya dalam penyebaran biji beberapa spesies pohon tropis.",
			Habitat:            "Hutan hujan tropis yang lebat",
			Food:               "Buah-buahan, terutama buah berdaging besar yang dapat memfasilitasi penyebaran biji",
			Reproduction:       "Bertelur dalam lubang pohon besar",
			FunFact:            "Paruh besar Enggang Gading tidak hanya fungsional untuk makan tapi juga berperan dalam ritual kawin dan dominasi teritorial.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Burung Hantu Celepuk",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               7,
			Hint:               "Burung hantu kecil yang aktif di malam hari",
			Description:        "Burung Hantu Celepuk adalah spesies burung hantu kecil yang ditemukan di berbagai habitat, dikenal akan mata besar dan kepala yang dapat berputar hampir 360 derajat.",
			Habitat:            "Hutan, area pertanian, dan kadang-kadang taman-taman di perkotaan",
			Food:               "Serangga kecil, tikus, dan kadang-kadang burung kecil lain",
			Reproduction:       "Bertelur dalam sarang yang ditinggalkan oleh burung lain atau di celah-celah pohon",
			FunFact:            "Meskipun kecil, Celepuk sangat efisien dalam berburu di malam hari berkat pendengaran yang sangat tajam dan penglihatan malam.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Kakatua Maluku",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               8,
			Hint:               "Burung ini berasal dari kepulauan Maluku",
			Description:        "Kakatua Maluku adalah salah satu spesies kakatua dengan warna bulu yang mencolok dan jambul yang khas, dikenal akan kepribadiannya yang ramah dan interaktif.",
			Habitat:            "Hutan tropis dan subtropis, serta beberapa area dekat pemukiman manusia",
			Food:               "Buah-buahan, kacang-kacangan, dan beberapa biji-bijian",
			Reproduction:       "Bertelur di lubang pohon",
			FunFact:            "Kakatua Maluku sangat cerdas, dapat menirukan suara dan melakukan trik-trik sederhana yang diajarkan oleh pemiliknya.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Anis Merah",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               9,
			Hint:               "Dikenal karena kicauannya yang merdu",
			Description:        "Anis Merah adalah burung kicau yang populer di Indonesia, sangat dicari karena suaranya yang khas dan melodis.",
			Habitat:            "Hutan tropis, area pertanian, dan taman",
			Food:               "Serangga kecil, buah-buahan, dan nektar",
			Reproduction:       "Bertelur di sarang yang terbuat dari ranting dan daun",
			FunFact:            "Anis Merah sering terlibat dalam kompetisi kicau burung, di mana kualitas suara mereka dievaluasi sebagai bagian dari kontes.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Burung Merpati Hutan",
			AnimalTypeID:       animalTypeMap["Aves"],
			Step:               10,
			Hint:               "Burung ini sering terlihat di hutan-hutan Indonesia",
			Description:        "Burung Merpati Hutan adalah spesies merpati yang lebih besar dan lebih kuat daripada merpati kota, dikenal karena kemampuannya beradaptasi di lingkungan hutan yang lebat.",
			Habitat:            "Hutan tropis dan subtropis",
			Food:               "Biji-bijian, buah-buahan, dan beberapa invertebrata kecil",
			Reproduction:       "Bertelur di sarang yang sederhana pada pohon atau semak",
			FunFact:            "Merpati Hutan memiliki kemampuan terbang yang sangat baik, sering terbang jarak jauh untuk mencari makanan.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Ikan Arwana",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               1,
			Hint:               "Ikan hias yang dipercaya membawa keberuntungan",
			Description:        "Ikan Arwana adalah ikan air tawar yang dianggap sebagai simbol keberuntungan dan kemakmuran, terutama di Asia.",
			Habitat:            "Sungai dan danau yang tenang",
			Food:               "Ikan kecil, serangga, dan kadang-kadang burung kecil",
			Reproduction:       "Bertelur, dengan perilaku mengasuh telur di mulut jantan",
			FunFact:            "Arwana dapat melompat tinggi dari air untuk menangkap mangsa seperti serangga atau bahkan burung kecil di atas air.",
			ConservationStatus: "Terancam (tergantung pada subspesies)",
		},
		{
			Name:               "Ikan Napoleon",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               2,
			Hint:               "Ikan karang besar dengan tonjolan dahi khas",
			Description:        "Ikan Napoleon adalah salah satu spesies ikan karang terbesar, dikenal dengan tonjolan dahi yang khas dan ukurannya yang mengesankan.",
			Habitat:            "Terumbu karang tropis",
			Food:               "Krustasea, moluska, dan ikan kecil",
			Reproduction:       "Bertelur, pelepasan telur dan sperma terjadi di perairan terbuka",
			FunFact:            "Ikan Napoleon mampu bertukar jenis kelamin dari betina menjadi jantan seiring bertambahnya usia.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Ikan Pari Manta",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               3,
			Hint:               "Ikan berbentuk piring dengan sirip dada yang lebar",
			Description:        "Ikan Pari Manta adalah salah satu spesies pari terbesar, terkenal dengan sirip dadanya yang sangat lebar dan mulut yang besar.",
			Habitat:            "Perairan hangat terbuka dan sepanjang terumbu karang",
			Food:               "Plankton, krustasea kecil, dan ikan kecil",
			Reproduction:       "Melahirkan, pari manta melahirkan satu anak pari yang sudah sepenuhnya terbentuk",
			FunFact:            "Meskipun ukurannya besar, pari manta adalah hewan yang lembut dan sering berinteraksi dengan penyelam.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Ikan Betta",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               4,
			Hint:               "Ikan hias kecil yang agresif saat bertemu sesamanya",
			Description:        "Ikan Betta, juga dikenal sebagai ikan cupang, adalah ikan hias yang populer karena warna cerah dan sirip yang indah.",
			Habitat:            "Air tawar, termasuk sawah dan rawa",
			Food:               "Serangga kecil, larva, dan zooplankton",
			Reproduction:       "Bertelur; jantan membangun sarang busa untuk menjaga telur",
			FunFact:            "Ikan Betta dikenal karena tingkah laku agresifnya terhadap ikan Betta lain, terutama jantan, yang menyebabkan mereka sering diadu dalam pertarungan.",
			ConservationStatus: "Kurang Prihatin",
		},
		{
			Name:               "Ikan Guppy",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               5,
			Hint:               "Ikan kecil yang mudah berbiak di akuarium",
			Description:        "Ikan Guppy, juga dikenal sebagai Millionfish, adalah ikan kecil yang populer di akuarium karena keindahan warna dan kemudahan perawatannya.",
			Habitat:            "Perairan tawar yang tenang, seperti sungai, rawa, dan kolam.",
			Food:               "Serangga kecil, larva, dan tumbuhan air.",
			Reproduction:       "Bertelur, dengan betina dapat menghasilkan banyak anak dalam satu kali kawin.",
			FunFact:            "Ikan Guppy dikenal sebagai ikan yang sangat produktif dalam berkembang biak, sehingga menjadi favorit bagi para penggemar akuarium.",
			ConservationStatus: "Tidak dinilai (Domestik)",
		},
		{
			Name:               "Ikan Tuna",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               6,
			Hint:               "Ikan yang sering diolah menjadi sashimi",
			Description:        "Ikan Tuna adalah ikan laut yang sangat penting secara ekonomi dan gizi, sering diolah menjadi sashimi, steak, atau kalengan.",
			Habitat:            "Perairan terbuka di lautan hangat dan sedang",
			Food:               "Ikan kecil, krustasea, dan cumi-cumi",
			Reproduction:       "Bertelur, dengan jutaan telur yang dikeluarkan dalam satu kali kawin",
			FunFact:            "Beberapa spesies tuna dapat melakukan migrasi jarak jauh, menempuh ribuan kilometer dalam pencarian makanan atau untuk berkembang biak.",
			ConservationStatus: "Rentan hingga Kritis (tergantung pada spesies)",
		},
		{
			Name:               "Ikan Parrot",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               7,
			Hint:               "Ikan tropis dengan warna cerah seperti burung beo",
			Description:        "Ikan Parrot, juga dikenal sebagai ikan Cichlid, adalah ikan tropis yang dikenal karena warna cerahnya dan kepribadiannya yang hidup.",
			Habitat:            "Perairan tawar, seperti sungai, danau, dan rawa-rawa",
			Food:               "Ular air, serangga, dan tumbuhan",
			Reproduction:       "Bertelur, dengan betina menjaga telur dan larva di dalam mulutnya",
			FunFact:            "Beberapa spesies ikan Parrot memiliki kemampuan untuk berkomunikasi dengan pemiliknya, menghasilkan suara yang meniru suara burung atau suara lingkungan.",
			ConservationStatus: "Tidak dinilai (Domestik)",
		},
		{
			Name:               "Ikan Kerapu",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               8,
			Hint:               "Populer di restoran seafood, terkenal akan teksturnya yang lembut",
			Description:        "Ikan Kerapu adalah ikan laut yang sangat dihargai dalam industri kuliner, terkenal karena dagingnya yang lembut dan rasanya yang lezat.",
			Habitat:            "Perairan hangat di sekitar terumbu karang atau perairan yang dalam",
			Food:               "Ikan kecil, udang, dan krustasea",
			Reproduction:       "Bertelur, dengan betina menghasilkan banyak telur yang disebarkan di air terbuka",
			FunFact:            "Beberapa spesies ikan Kerapu dapat tumbuh menjadi sangat besar, dengan berat mencapai ratusan kilogram.",
			ConservationStatus: "Bervariasi tergantung pada spesies (dari Tidak Dinilai hingga Rentan)",
		},
		{
			Name:               "Ikan Teri",
			AnimalTypeID:       animalTypeMap["Pisces"],
			Step:               9,
			Hint:               "Ikan kecil yang sering dijadikan sebagai camilan gurih",
			Description:        "Ikan Teri adalah ikan kecil yang populer sebagai camilan gurih dan bahan tambahan dalam berbagai masakan tradisional.",
			Habitat:            "Perairan tawar dan air payau, serta kadang-kadang di perairan laut dangkal",
			Food:               "Plankton dan detritus organik",
			Reproduction:       "Bertelur, dengan betina menghasilkan banyak telur yang menempel pada substrat di perairan dangkal",
			FunFact:            "Ikan Teri adalah salah satu sumber protein yang penting dalam makanan sehari-hari di beberapa wilayah.",
			ConservationStatus: "Tidak dinilai",
		},
		{
			Name:               "Orangutan",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               1,
			Hint:               "Primata besar dengan bulu merah",
			Description:        "Orangutan adalah spesies primata besar yang endemik di pulau Borneo dan Sumatera. Mereka dikenal karena kemampuan mereka dalam menggunakan alat dan lingkungan hutan.",
			Habitat:            "Hutan tropis, terutama hutan dataran rendah hingga pegunungan",
			Food:               "Buah-buahan, daun, tunas, serangga, dan madu",
			Reproduction:       "Melahirkan, dengan periode kehamilan sekitar 8-9 bulan",
			FunFact:            "Orangutan adalah salah satu satwa endemik yang terancam punah karena perusakan habitat dan perdagangan ilegal.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Harimau Sumatera",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               2,
			Hint:               "Kucing besar dengan loreng hitam",
			Description:        "Harimau Sumatera adalah subspesies harimau yang hanya ditemukan di pulau Sumatera, terkenal karena ukurannya yang lebih kecil dibandingkan dengan harimau dari daratan Asia.",
			Habitat:            "Hutan hujan tropis, termasuk hutan dataran rendah dan pegunungan",
			Food:               "Rusa, babi hutan, dan kadang-kadang ikan",
			Reproduction:       "Melahirkan, dengan periode kehamilan sekitar 3-4 bulan dan biasanya melahirkan 2-3 anak",
			FunFact:            "Harimau Sumatera adalah spesies harimau yang paling kecil dan dianggap sebagai salah satu predator puncak di habitatnya.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Gajah Sumatera",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               3,
			Hint:               "Mamalia besar dengan belalai panjang",
			Description:        "Gajah Sumatera adalah subspesies gajah Asia yang lebih kecil dan memiliki telinga yang lebih kecil dibandingkan dengan gajah Afrika.",
			Habitat:            "Hutan hujan tropis dan area dataran rendah di sekitar sumber air",
			Food:               "Herbivora yang makan berbagai tumbuhan, termasuk pohon muda, rumput, buah, dan kulit pohon",
			Reproduction:       "Melahirkan, dengan periode kehamilan sekitar 22 bulan",
			FunFact:            "Gajah Sumatera sering berkolaborasi dalam kelompok matriarkal dan memainkan peran penting dalam menjaga keseimbangan ekologi hutan.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Badak Jawa",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               4,
			Hint:               "Hewan dengan satu cula di atas hidung",
			Description:        "Badak Jawa adalah salah satu dari lima spesies badak yang tersisa di dunia, dan merupakan salah satu yang paling terancam punah.",
			Habitat:            "Hutan hujan tropis, terutama di area yang terpencil dan jarang terganggu oleh aktivitas manusia",
			Food:               "Herbivora, makan daun, pucuk, buah, dan cabang pohon",
			Reproduction:       "Melahirkan, biasanya satu anak setiap interval 2-3 tahun",
			FunFact:            "Badak Jawa dikenal karena sifatnya yang pemalu dan sulit dideteksi, sering menciptakan jalur lumpur yang digunakan berulang kali untuk berpindah tempat.",
			ConservationStatus: "Kritis",
		},
		{
			Name:               "Anoa",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               5,
			Hint:               "Bison kecil endemik dari Sulawesi",
			Description:        "Anoa adalah jenis kerbau kerdil yang hanya ditemukan di pulau Sulawesi, sering disebut sebagai 'Kerbau Kerdil'.",
			Habitat:            "Hutan tropis dan area sabana di Sulawesi",
			Food:               "Herbivora, makan rumput, daun, dan buah",
			Reproduction:       "Melahirkan satu anak setiap kali, dengan periode kehamilan sekitar 9-10 bulan",
			FunFact:            "Anoa memiliki temperamen yang agresif jika terpojok, meskipun ukurannya relatif kecil untuk sejenis kerbau.",
			ConservationStatus: "Terancam",
		},
		{
			Name:               "Tapir",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               6,
			Hint:               "Memiliki moncong panjang seperti belalai",
			Description:        "Tapir adalah hewan besar dengan moncong yang unik yang berfungsi seperti belalai mini, memudahkannya untuk meraih makanan.",
			Habitat:            "Hutan hujan tropis dan area yang dekat dengan sumber air",
			Food:               "Herbivora, makan daun, buah-buahan, dan cabang pohon",
			Reproduction:       "Melahirkan satu anak setiap interval 2 tahun",
			FunFact:            "Tapir adalah perenang yang sangat baik dan sering menggunakan air sebagai tempat perlindungan dari pemangsa.",
			ConservationStatus: "Terancam",
		},
		{
			Name:               "Monyet Ekor Panjang",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               7,
			Hint:               "Monyet yang sering ditemui di seluruh wilayah Indonesia",
			Description:        "Monyet Ekor Panjang, juga dikenal sebagai Macaque, adalah primata yang sangat adaptif dan sering ditemukan dekat pemukiman manusia serta hutan.",
			Habitat:            "Hutan, area pedesaan, dan kadang-kadang di perkotaan",
			Food:               "Omnivora, makan buah, biji-bijian, serangga, dan kadang-kadang makanan dari manusia",
			Reproduction:       "Melahirkan, biasanya satu anak",
			FunFact:            "Monyet ini sering terlibat dalam interaksi sosial yang kompleks dan dapat menunjukkan berbagai perilaku yang cerdas, seperti menggunakan alat untuk mendapatkan makanan.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Tarsius Sulawesi",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               8,
			Hint:               "Primata kecil dengan mata besar",
			Description:        "Tarsius Sulawesi, atau Tarsier, adalah primata kecil yang dikenal karena mata besar dan kaki yang sangat panjang relatif terhadap ukuran tubuhnya, adaptasi untuk melompat antar pohon.",
			Habitat:            "Hutan tropis",
			Food:               "Karnivora, makan terutama serangga dan kadang-kadang reptil kecil atau burung",
			Reproduction:       "Melahirkan satu anak",
			FunFact:            "Tarsius adalah salah satu primata paling kecil di dunia dan memiliki kemampuan luar biasa untuk memutar kepalanya hampir 180 derajat.",
			ConservationStatus: "Terancam",
		},
		{
			Name:               "Beruang Madu",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               9,
			Hint:               "Beruang kecil dari Asia Tenggara",
			Description:        "Beruang Madu, juga dikenal sebagai Sun Bear, adalah beruang terkecil dari spesies beruang dan dikenal akan ciri khasnya yaitu bulu dada yang berbentuk seperti bulan sabit.",
			Habitat:            "Hutan tropis lembap",
			Food:               "Omnivora, makan buah-buahan, madu, serangga, dan kadang-kadang kecil vertebrata",
			Reproduction:       "Melahirkan, biasanya dua anak",
			FunFact:            "Beruang Madu memiliki lidah yang sangat panjang, yang digunakan untuk mengambil madu dari sarang lebah.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Rusa Timor",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               10,
			Hint:               "Rusa yang banyak ditemukan di Nusa Tenggara",
			Description:        "Rusa Timor adalah jenis rusa yang banyak ditemukan di kepulauan Nusa Tenggara dan sekitarnya, dikenal karena adaptasinya yang baik terhadap berbagai habitat.",
			Habitat:            "Hutan terbuka, padang rumput, dan area pertanian",
			Food:               "Herbivora, makan rumput dan tumbuhan lainnya",
			Reproduction:       "Bertelur, sering dalam kelompok yang dikendalikan oleh seekor jantan dominan",
			FunFact:            "Rusa Timor sering berinteraksi sosial dan menggunakan tanduk mereka dalam ritual pertarungan selama musim kawin.",
			ConservationStatus: "Rentan",
		},
		{
			Name:               "Banteng",
			AnimalTypeID:       animalTypeMap["Mamalia"],
			Step:               11,
			Hint:               "Mempunyai dua tanduk dan sering ditemukan di Jawa",
			Description:        "Banteng adalah jenis sapi liar yang asli Asia Tenggara, dikenal karena dua tanduk yang tajam dan postur yang kuat.",
			Habitat:            "Hutan, padang rumput, dan area savana",
			Food:               "Herbivora, makan rumput dan dedaunan",
			Reproduction:       "Melahirkan satu anak setelah periode kehamilan sekitar 9 bulan",
			FunFact:            "Banteng adalah leluhur dari beberapa jenis sapi domestik dan masih dihormati dalam beberapa budaya lokal karena kekuatan dan keindahan mereka.",
			ConservationStatus: "Terancam",
		},
	}

	hasTable := db.Migrator().HasTable(&entity.Animal{})
	if !hasTable {
		if err := db.Migrator().CreateTable(&entity.Animal{}); err != nil {
			return nil, err
		}
	}

	for _, data := range dummyAnimals {
		var animal entity.Animal
		err := db.Where(&entity.Animal{Name: data.Name}).First(&animal).Error
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, err
		}

		isData := db.Find(&animal, "name = ?", data.Name).RowsAffected
		if isData == 0 {
			if err := db.Create(&data).Error; err != nil {
				return nil, err
			}
		}
	}

	var curAnimals []entity.Animal
	if err := db.Find(&curAnimals).Error; err != nil {
		return nil, err
	}

	animalMap := map[string]string{}
	for _, data := range curAnimals {
		animalMap[data.Name] = data.ID.String()
	}
	return animalMap, nil
}
